version: '3.4'

services:
  webui:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "SpaBaseUrl=http://client-app:4200"

  client-app:
    image: ${DOCKER_REGISTRY-}client-app
    build:
      context: src/WebUI/client-app
      dockerfile: Dockerfile
    depends_on:
      - webui
    restart: on-failure

  db:
    ports:
      - "1433:1433"